version: "3.8"

services:
  postgres:
    container_name: postgres-sql-ebook
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ebook
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spring-ebook
    restart: unless-stopped

networks:
  spring-ebook:
    driver: bridge

volumes:
  postgres:
    driver: local